# Pilot Case Review

Inspection notebook for the pilot coding subset. This notebook reads the pilot CSV and summarizes coverage and missingness without modifying any data.

In [1]:
from pathlib import Path

import pandas as pd

pd.set_option("display.max_rows", 200)
pd.set_option("display.max_columns", 200)

In [2]:
project_root = Path.cwd()
pilot_path = project_root / "data" / "interim" / "pilot_coding_sheet.csv"

if not pilot_path.exists():
    project_root = Path.cwd().parent
    pilot_path = project_root / "data" / "interim" / "pilot_coding_sheet.csv"

if not pilot_path.exists():
    raise FileNotFoundError(f"Pilot dataset not found at {pilot_path}")

pilot_path

WindowsPath('d:/ADRIAN/projects/Collapse_Pathways/data/interim/pilot_coding_sheet.csv')

In [3]:
df = pd.read_csv(pilot_path)
df.head()

,case_id,case_name,case_type,region,period_start,period_end,time_window_years,phase_label,collapse_outcome,collapse_within_next_window,political_fragmentation,elite_conflict,succession_crisis,legitimacy_crisis,administrative_overload,corruption_governance_failure,social_inequality,social_unrest_rebellion,demographic_pressure,migration_pressure,ethnic_sectarian_fragmentation,urban_decline,fiscal_crisis,taxation_extraction_pressure,trade_disruption,inflation_currency_instability,resource_dependency,agricultural_decline,drought_climate_stress,flood_environmental_shock,temperature_anomaly,ecological_degradation,food_insecurity,external_invasion_pressure,civil_war_internal_conflict,military_overstretch,territorial_loss,institutional_rigidity,adaptive_capacity,logistics_food_storage_resilience,alliance_network_strength,recovery_capacity,data_confidence,source_count,notes
0,rome_west_-100_-75,Western Roman Empire,ancient,Mediterranean,-100,-75,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,rome_west_-75_-50,Western Roman Empire,ancient,Mediterranean,-75,-50,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,rome_west_-50_-25,Western Roman Empire,ancient,Mediterranean,-50,-25,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,rome_west_-25_0,Western Roman Empire,ancient,Mediterranean,-25,0,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,rome_west_0_25,Western Roman Empire,ancient,Mediterranean,0,25,25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## Dataset Shape

In [4]:
print(f"Rows: {df.shape[0]}")
print(f"Columns: {df.shape[1]}")

Rows: 43
Columns: 45

## Row Counts By Case

In [5]:
row_counts = (
    df["case_name"]
    .value_counts()
    .rename_axis("case_name")
    .reset_index(name="row_count")
)

row_counts

              case_name  row_count
0  Western Roman Empire         24
1                  Maya         14
2          Soviet Union          5

## Time Windows For Each Case

In [6]:
time_windows = (
    df[["case_name", "case_id", "period_start", "period_end", "time_window_years"]]
    .sort_values(["case_name", "period_start", "period_end"])
    .reset_index(drop=True)
)

time_windows

,case_name,case_id,period_start,period_end,time_window_years
0,Maya,maya_600_625,600,625,25
1,Maya,maya_625_650,625,650,25
2,Maya,maya_650_675,650,675,25
3,Maya,maya_675_700,675,700,25
4,Maya,maya_700_725,700,725,25
5,Maya,maya_725_750,725,750,25
6,Maya,maya_750_775,750,775,25
7,Maya,maya_775_800,775,800,25
8,Maya,maya_800_825,800,825,25
9,Maya,maya_825_850,825,850,25
10,Maya,maya_850_875,850,875,25
11,Maya,maya_875_900,875,900,25
12,Maya,maya_900_925,900,925,25
13,Maya,maya_925_950,925,950,25
14,Soviet Union,ussr_1950_1960,1950,1960,10
15,Soviet Union,ussr_1960_1970,1960,1970,10
16,Soviet Union,ussr_1970_1980,1970,1980,10
17,Soviet Union,ussr_1980_1990,1980,1990,10
18,Soviet Union,ussr_1990_1991,1990,1991,1
19,Western Roman Empire,rome_west_-100_-75,-100,-75,25
20,Western Roman Empire,rome_west_-75_-50,-75,-50,25
21,Western Roman Empire,rome_west_-50_-25,-50,-25,25
22,Western Roman Empire,rome_west_-25_0,-25,0,25
23,Western Roman Empire,rome_west_0_25,0,25,25
24,Western Roman Empire,rome_west_25_50,25,50,25
25,Western Roman Empire,rome_west_50_75,50,75,25
26,Western Roman Empire,rome_west_75_100,75,100,25
27,Western Roman Empire,rome_west_100_125,100,125,25
28,Western Roman Empire,rome_west_125_150,125,150,25
29,Western Roman Empire,rome_west_150_175,150,175,25
30,Western Roman Empire,rome_west_175_200,175,200,25
31,Western Roman Empire,rome_west_200_225,200,225,25
32,Western Roman Empire,rome_west_225_250,225,250,25
33,Western Roman Empire,rome_west_250_275,250,275,25
34,Western Roman Empire,rome_west_275_300,275,300,25
35,Western Roman Empire,rome_west_300_325,300,325,25
36,Western Roman Empire,rome_west_325_350,325,350,25
37,Western Roman Empire,rome_west_350_375,350,375,25
38,Western Roman Empire,rome_west_375_400,375,400,25
39,Western Roman Empire,rome_west_400_425,400,425,25
40,Western Roman Empire,rome_west_425_450,425,450,25
41,Western Roman Empire,rome_west_450_475,450,475,25
42,Western Roman Empire,rome_west_475_500,475,500,25

## Fields That Are Still Empty

In [7]:
missing_summary = (
    pd.DataFrame({
        "missing_count": df.isna().sum(),
        "missing_pct": df.isna().mean().mul(100),
    })
    .sort_values(["missing_count", "missing_pct"], ascending=False)
)

missing_summary[missing_summary["missing_count"] > 0]

                                   missing_count  missing_pct
phase_label                                   43        100.0
collapse_outcome                              43        100.0
collapse_within_next_window                   43        100.0
political_fragmentation                       43        100.0
elite_conflict                                43        100.0
succession_crisis                             43        100.0
legitimacy_crisis                             43        100.0
administrative_overload                       43        100.0
corruption_governance_failure                 43        100.0
social_inequality                             43        100.0
social_unrest_rebellion                       43        100.0
demographic_pressure                          43        100.0
migration_pressure                            43        100.0
ethnic_sectarian_fragmentation                43        100.0
urban_decline                                 43        100.0
fiscal_crisis                                 43        100.0
taxation_extraction_pressure                  43        100.0
trade_disruption                              43        100.0
inflation_currency_instability                43        100.0
resource_dependency                           43        100.0
agricultural_decline                          43        100.0
drought_climate_stress                        43        100.0
flood_environmental_shock                     43        100.0
temperature_anomaly                           43        100.0
ecological_degradation                        43        100.0
food_insecurity                               43        100.0
external_invasion_pressure                    43        100.0
civil_war_internal_conflict                   43        100.0
military_overstretch                          43        100.0
territorial_loss                              43        100.0
institutional_rigidity                        43        100.0
adaptive_capacity                             43        100.0
logistics_food_storage_resilience             43        100.0
alliance_network_strength                     43        100.0
recovery_capacity                             43        100.0
data_confidence                               43        100.0
source_count                                  43        100.0
notes                                         43        100.0

In [8]:
fully_empty_fields = missing_summary[missing_summary["missing_count"] == len(df)]
fully_empty_fields

                                   missing_count  missing_pct
phase_label                                   43        100.0
collapse_outcome                              43        100.0
collapse_within_next_window                   43        100.0
political_fragmentation                       43        100.0
elite_conflict                                43        100.0
succession_crisis                             43        100.0
legitimacy_crisis                             43        100.0
administrative_overload                       43        100.0
corruption_governance_failure                 43        100.0
social_inequality                             43        100.0
social_unrest_rebellion                       43        100.0
demographic_pressure                          43        100.0
migration_pressure                            43        100.0
ethnic_sectarian_fragmentation                43        100.0
urban_decline                                 43        100.0
fiscal_crisis                                 43        100.0
taxation_extraction_pressure                  43        100.0
trade_disruption                              43        100.0
inflation_currency_instability                43        100.0
resource_dependency                           43        100.0
agricultural_decline                          43        100.0
drought_climate_stress                        43        100.0
flood_environmental_shock                     43        100.0
temperature_anomaly                           43        100.0
ecological_degradation                        43        100.0
food_insecurity                               43        100.0
external_invasion_pressure                    43        100.0
civil_war_internal_conflict                   43        100.0
military_overstretch                          43        100.0
territorial_loss                              43        100.0
institutional_rigidity                        43        100.0
adaptive_capacity                             43        100.0
logistics_food_storage_resilience             43        100.0
alliance_network_strength                     43        100.0
recovery_capacity                             43        100.0
data_confidence                               43        100.0
source_count                                  43        100.0
notes                                         43        100.0